name: Validate YAML parameters of an OpenFisca-based tax-benefit system
on:
  workflow_call:
    inputs:
      event_name:
        description: 'name of event that triggered the workflow (GITHUB_EVENT_NAME)'
        required: true
        type: string
      parameters_path:
        description: 'path of parameters in repository (eg "openfisca_france/parameters")'
        required: true
        type: string
      ref:
        description: 'branch or tag ref that triggered the workflow (GITHUB_REF)'
        required: false
        type: string
      ref_type:
        description: 'type of ref that triggered the workflow (either "branch" or "tag") (GITHUB_REF_TYPE)'
        required: false
        type: string
      repository:
        description: 'owner and repository name. For example, "octocat/Hello-World" (GITHUB_REPOSITORY)'
        required: true
        type: string
    secrets:
      token:
        description: 'Secret token needed to access Tax-Benefit control-center'
        required: true
jobs:
  validate:
    name: Call Tax-Benefit YAML validator
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_NAME: ${{ toJSON(inputs.event_name) }}
          PARAMETERS_PATH: ${{ toJSON(inputs.parameters_path) }}
          REF: ${{ toJSON(inputs.ref) }}
          REF_TYPE: ${{ toJSON(inputs.ref_type) }}
          REPOSITORY: ${{ toJSON(inputs.repository) }}
          TOKEN: ${{ toJSON(inputs.token) }}
        run: env
      - env:
          EVENT_NAME: ${{ toJSON(inputs.event_name) }}
          PARAMETERS_PATH: ${{ toJSON(inputs.parameters_path) }}
          REF: ${{ toJSON(inputs.ref) }}
          REF_TYPE: ${{ toJSON(inputs.ref_type) }}
          REPOSITORY: ${{ toJSON(inputs.repository) }}
          TOKEN: ${{ toJSON(inputs.token) }}
        run: |
          curlf() {
            # See https://superuser.com/questions/590099/can-i-make-curl-fail-with-an-exitcode-different-than-0-if-the-http-status-code-i
            OUTPUT_FILE=$(mktemp)
            HTTP_CODE=$(curl --silent --output $OUTPUT_FILE --write-out "%{http_code}" "$@")
            if [[ ${HTTP_CODE} -lt 200 || ${HTTP_CODE} -gt 299 ]] ; then
              >&2 cat $OUTPUT_FILE
              return 22
            fi
            cat $OUTPUT_FILE
            rm $OUTPUT_FILE
          }
          env | curlf --data-binary @- --header "Content-Type: text/plain; charset=utf-8" --max-time 300 https://control-center.tax-benefit.org/github/validate_yaml.json
